// Code generated by reset generator. DO NOT EDIT.
package storage

func (s *savedURLItem) Reset() {
	if s == nil {
		return
	}

	s.UUID = ""

	s.ShortURL = ""

	s.OriginalURL = ""

	s.UserID = 0

}

func (s *savedUserItem) Reset() {
	if s == nil {
		return
	}

	s.UUID = ""

	s.ID = 0

}

func (m *MemoryStorage) Reset() {
	if m == nil {
		return
	}

	clear(m.Urls)

	clear(m.Users)

	m.UseFile = false

	m.DataFilePath = ""

}

func (p *PostgresStorage) Reset() {
	if p == nil {
		return
	}

}

func (u *URL) Reset() {
	if u == nil {
		return
	}

	u.Code = ""

	u.URL = ""

	u.UserID = 0

	u.isDeleted = false

}

func (u *User) Reset() {
	if u == nil {
		return
	}

	u.ID = 0

}
