// Code generated by reset generator. DO NOT EDIT.
package handler

func (h *Handler) Reset() {
	if h == nil {
		return
	}

}

func (c *compressWriter) Reset() {
	if c == nil {
		return
	}

}

func (c *compressReader) Reset() {
	if c == nil {
		return
	}

}
