// Code generated by reset generator. DO NOT EDIT.
package repository

func (r *RemoteAuditObserver) Reset() {
	if r == nil {
		return
	}

	r.url = ""

}

func (d *deleteURLsTask) Reset() {
	if d == nil {
		return
	}

	d.UserID = 0

	d.Codes = d.Codes[:0]

}

func (d *DeleteURLsWorkers) Reset() {
	if d == nil {
		return
	}

	d.batchSize = 0

}

func (a *AuditEvent) Reset() {
	if a == nil {
		return
	}

	a.TS = 0

	a.Action = ""

	a.UserID = 0

	a.URL = ""

}

func (a *AuditPublisher) Reset() {
	if a == nil {
		return
	}

	a.observers = a.observers[:0]

}

func (f *FileAuditObserver) Reset() {
	if f == nil {
		return
	}

	f.filePath = ""

}
