// Code generated by reset generator. DO NOT EDIT.
package main

func (j *JSONGenerateURLRequest) Reset() {
	if j == nil {
		return
	}

	j.URL = ""

}

func (j *JSONGenerateURLResponse) Reset() {
	if j == nil {
		return
	}

	j.Result = ""

}
