// Code generated by reset generator. DO NOT EDIT.
package model

func (j *JSONGenerateURLRequest) Reset() {
	if j == nil {
		return
	}

	j.URL = ""

}

func (j *JSONGenerateURLResponse) Reset() {
	if j == nil {
		return
	}

	j.Result = ""

}

func (b *BatchGenerateURLRequest) Reset() {
	if b == nil {
		return
	}

	b.CorrelationID = ""

	b.URL = ""

}

func (b *BatchGenerateURLResponse) Reset() {
	if b == nil {
		return
	}

	b.CorrelationID = ""

	b.ShortURL = ""

}

func (u *UserURLsResponse) Reset() {
	if u == nil {
		return
	}

	u.ShortURL = ""

	u.OriginalURL = ""

}
