// Code generated by reset generator. DO NOT EDIT.
package config

func (c *Config) Reset() {
	if c == nil {
		return
	}

	c.RunAddr = ""

	c.ServerAddr = ""

	c.DataFilePath = ""

	c.DatabaseDsn = ""

	c.MigrationsPath = ""

	c.DevMode = false

	c.SecretKey = ""

	c.TokenExp = 0

	c.DeleteBatchSize = 0

	c.DeleteTimeDuration = 0

	c.AuditFile = ""

	c.AuditURL = ""

}
